name = "dusd"
chain = "mainnet"
address = "0x6b006870c83b1cd49e766ac9209f8d68763df721"

[calibers.mainnet]
address = "0xd1a1c248b253f1fc60eacd90777b9a63f8c8c1bc"
swapper = "0x923c98b22F9c367A109E93f7dfBaCa28b20C17C3"
rootfiles = "github:MakinaHQ/config/machines/dusd/mainnet/rootfiles"

[calibers.mainnet.accounting_token]
address = "0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48"
decimals = 6
name = "USD Coin"
symbol = "USDC"
